name: Java CI-CD to AWS

on:
  push:
    branches:
      - main
      - master

  workflow_dispatch:

env:
  AWS_REGION: ap-southeast-2
  ECR_REPOSITORY: calculator-app
  CONTAINER_NAME: calculator-app
  CONTAINER_PORT: 8081
  HOST_PORT: 8081   

jobs:

  # ==========================================================
  # JOB 1 - BUILD AND PUSH DOCKER IMAGE TO ECR
  # ==========================================================
  build-and-push:
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Install Java
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      # 3. Check Java version
      - name: Check Java version
        run: java -version

      # 4. Maven test
      - name: Maven test
        run: mvn clean test

      # 5. Maven build
      - name: Maven build
        run: mvn clean package -DskipTests

      # 6. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 7. Login to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 8. Build Docker image
      - name: Build Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }} .
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }} \
            $ECR_REGISTRY/$ECR_REPOSITORY:latest

      # 9. Push Docker image to ECR
      - name: Push Docker image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest


  # ==========================================================
  # JOB 2 - DEPLOY TO EC2
  # ==========================================================
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:

      # 1. SSH into EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
          CONTAINER_NAME: ${{ env.CONTAINER_NAME }}
          CONTAINER_PORT: ${{ env.CONTAINER_PORT }}
          HOST_PORT: ${{ env.HOST_PORT }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: AWS_REGION,ECR_REPOSITORY,CONTAINER_NAME,CONTAINER_PORT,HOST_PORT,AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,ECR_REGISTRY
          script: |

            echo "===== Login to ECR ====="

            aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
            aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
            aws configure set region "$AWS_REGION"
            
            aws ecr get-login-password --region ap-southeast-2 | \
            docker login --username AWS --password-stdin \
            671830949187.dkr.ecr.ap-southeast-2.amazonaws.com

            echo "===== Pull latest image ====="

            docker pull \
              671830949187.dkr.ecr.ap-southeast-2.amazonaws.com/calculator-app:latest

#            echo "===== Stop old container ====="
#
#            docker stop "$CONTAINER_NAME" || true
#
#
#            echo "===== Remove old container ====="
#
#            docker rm "$CONTAINER_NAME" || true


            echo "===== Run new container ====="
                    
             docker run -d \
             --name calculator-app \
             -p 8081:8081 \
              671830949187.dkr.ecr.ap-southeast-2.amazonaws.com/calculator-app:latest

            echo "===== Deployment completed ====="

            docker ps
            
